Title: Saving Vertical Space
Author: David M. Bradford
Base Header Level:  2

<whatever>
The *first* thing I did is to delete the first of this pair of lines, which was redundant, because the line that follows also checks the format of the input:
</bleh>

<pre>
   1 <span class="k">die</span> <span class="k">unless</span> <span class="i">$input</span> =~ <span class="q">/d/</span><span class="sc">;</span>
   2 <span class="k">if</span> <span class="s">(</span> <span class="i">$input</span> =~ <span class="q">/(\d*)d(\d+)\s*(\D?)\s*(\d*)/</span> <span class="s">)</span> <span class="s">{</span>
</pre>


But instead of having that big `if` block, I changed it to this:

<pre>
   1 <span class="k">return</span> <span class="k">unless</span> <span class="i">$input</span> =~ <span class="q">/(\d*)d(\d+)\s*(\D?)\s*(\d*)/</span><span class="sc">;</span>
</pre>


Then I combined these:

