The *first* thing I did is to delete the first of this pair of lines, which was redundant, because the line that follows also checks the format of the input:
<perl old>
*die* unless $input =~ /d/;
if ( $input =~ /(\d*)d(\d+)\s*(\D?)\s*(\d*)/ ) {
</perl>
But instead of having that big `if` block, I changed it to this:
<perl>
return unless $input =~ /(\d*)d(\d+)\s*(\D?)\s*(\d*)/;
</perl>
Then I combined these:
